package types

import "github.com/go-gota/gota/series"

var CSVColumnMapping = map[string]series.Type{
	"report_period_start":            series.String,
	"report_period_end":              series.String,
	"interval_start":                 series.String,
	"interval_end":                   series.String,
	"container_name":                 series.String,
	"pod":                            series.String,
	"owner_name":                     series.String,
	"owner_kind":                     series.String,
	"workload":                       series.String,
	"workload_type":                  series.String,
	"namespace":                      series.String,
	"image_name":                     series.String,
	"node":                           series.String,
	"resource_id":                    series.String,
	"cpu_request_container_avg":      series.Float,
	"cpu_request_container_sum":      series.Float,
	"cpu_limit_container_avg":        series.Float,
	"cpu_limit_container_sum":        series.Float,
	"cpu_usage_container_avg":        series.Float,
	"cpu_usage_container_min":        series.Float,
	"cpu_usage_container_max":        series.Float,
	"cpu_usage_container_sum":        series.Float,
	"cpu_throttle_container_avg":     series.Float,
	"cpu_throttle_container_max":     series.Float,
	"cpu_throttle_container_sum":     series.Float,
	"memory_request_container_avg":   series.Float,
	"memory_request_container_sum":   series.Float,
	"memory_limit_container_avg":     series.Float,
	"memory_limit_container_sum":     series.Float,
	"memory_usage_container_avg":     series.Float,
	"memory_usage_container_min":     series.Float,
	"memory_usage_container_max":     series.Float,
	"memory_usage_container_sum":     series.Float,
	"memory_rss_usage_container_avg": series.Float,
	"memory_rss_usage_container_min": series.Float,
	"memory_rss_usage_container_max": series.Float,
	"memory_rss_usage_container_sum": series.Float,
}

var NamespaceCSVColumnMapping = map[string]series.Type{
	"report_period_start":            series.String,
	"report_period_end":              series.String,
	"interval_start":                 series.String,
	"interval_end":                   series.String,
	"namespace":                      series.String,
	"cpu_request_namespace_sum":      series.Float,
	"cpu_limit_namespace_sum":        series.Float,
	"cpu_usage_namespace_avg":        series.Float,
	"cpu_usage_namespace_max":        series.Float,
	"cpu_usage_namespace_min":        series.Float,
	"cpu_throttle_namespace_avg":     series.Float,
	"cpu_throttle_namespace_max":     series.Float,
	"cpu_throttle_namespace_min":     series.Float,
	"memory_request_namespace_sum":   series.Float,
	"memory_limit_namespace_sum":     series.Float,
	"memory_usage_namespace_avg":     series.Float,
	"memory_usage_namespace_max":     series.Float,
	"memory_usage_namespace_min":     series.Float,
	"memory_rss_usage_namespace_avg": series.Float,
	"memory_rss_usage_namespace_max": series.Float,
	"memory_rss_usage_namespace_min": series.Float,
	"namespace_running_pods_max":     series.Float,
	"namespace_running_pods_avg":     series.Float,
	"namespace_total_pods_max":       series.Float,
	"namespace_total_pods_avg":       series.Float,
}
