version: "2"
linters:
  enable:
    - bodyclose
    - godot
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - unparam
    - govet
  settings:
    errcheck:
        exclude-functions:
        - fmt.Fprintln
        - fmt.Fprint

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
