version: "2"
linters:
  enable:
    - bodyclose
    - godot
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - unparam
    - govet
    - gosec
    # TODO: enable gocritic with performance tag
    # - gocritic
  settings:
    # gocritic:
    #   disable-all: true
    #   enabled-tags:
    #     - performance
    errcheck:
      exclude-functions:
        - fmt.Fprintln
        - fmt.Fprint

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
