---
apiVersion: v1
kind: Template
metadata:
  name: ros-ocp-backend
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ros-ocp-backend
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - ingress
    - rbac
    deployments:
    - name: processor
      replicas: ${{PROCESSOR_REPLICA_COUNT}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start processor"]
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: KRUIZE_HOST
            value: ${KRUIZE_HOST}
          - name: KRUIZE_PORT
            value: ${KRUIZE_PORT}
          - name: KRUIZE_WAIT_TIME
            value: ${KRUIZE_WAIT_TIME}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
    - name: recommender
      replicas: ${{RECOMMENDER_REPLICA_COUNT}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start recommender"]
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: KRUIZE_HOST
            value: ${KRUIZE_HOST}
          - name: KRUIZE_PORT
            value: ${KRUIZE_PORT}
          - name: KRUIZE_WAIT_TIME
            value: ${KRUIZE_WAIT_TIME}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
    - name: api
      replicas: ${{API_REPLICA_COUNT}}
      webServices:
        public:
          enabled: true
          apiPath: cost-management
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start api"]
        resources:
          requests:
            cpu: ${CPU_REQUEST}
            memory: ${MEMORY_REQUEST}
          limits:
            cpu: ${CPU_LIMIT}
            memory: ${MEMORY_LIMIT}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        env:
          - name: PATH_PREFIX
            value: /api
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: ENABLE_RBAC
            value: "${ENABLE_RBAC}"
          - name: DB_POOL_SIZE
            value: ${DB_POOL_SIZE}
          - name: DB_MAX_OVERFLOW
            value: ${DB_MAX_OVERFLOW}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
    - name: kruize
      replicas: ${{KRUIZE_REPLICA_COUNT}}
      webServices:
        private:
          enabled: true
      podSpec:
        image: ${KRUIZE_IMAGE}:${KRUIZE_IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "export DB_CONFIG_FILE=${ACG_CONFIG} && bash target/bin/Autotune"]
        resources:
          requests:
            cpu: ${KRUIZE_CPU_REQUEST}
            memory: ${KRUIZE_MEMORY_REQUEST}
          limits:
            cpu: ${KRUIZE_CPU_LIMIT}
            memory: ${KRUIZE_MEMORY_LIMIT}
        env:
          - name: AUTOTUNE_SERVER_PORT
            value: ${KRUIZE_PORT}
          - name: AUTH_TOKEN
            value: ""
          - name: LOGGING_LEVEL
            value: "info"
          - name: ROOT_LOGGING_LEVEL
            value: "info"
          - name: dbdriver
            value: "jdbc:postgresql://"
          - name: database_name
            value: ${KRUIZE_DB_NAME}
          - name: clustertype
            value: "kubernetes"
          - name: k8stype
            value: "openshift"
          - name: authtype
            value: "openshift"
          - name: monitoringagent
            value: "prometheus"
          - name: monitoringservice
            value: "prometheus-k8s"
          - name: monitoringendpoint
            value: "prometheus-k8s"
          - name: savetodb
            value: "true"
          - name: hibernate_dialect
            value: "org.hibernate.dialect.PostgreSQLDialect"
          - name: hibernate_driver
            value: "org.postgresql.Driver"
          - name: hibernate_c3p0minsize
            value: "2"
          - name: hibernate_c3p0maxsize
            value: "5"
          - name: hibernate_c3p0timeout
            value: "300"
          - name: hibernate_c3p0maxstatements
            value: "50"
          - name: hibernate_hbm2ddlauto
            value: "update"
          - name: hibernate_showsql
            value: "false"
          - name: hibernate_timezone
            value: "UTC"
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
    database:
      name: rosocp
      version: 13
    kafkaTopics:
      - topicName: hccm.ros.events
        partitions: 1
      - topicName: rosocp.kruize.experiments
        partitions: 1

parameters:
- description : ClowdEnvironment name
  name: ENV_NAME
  required: true
- description: Replica count for processor pod
  name: PROCESSOR_REPLICA_COUNT
  value: "1"
- description: Image NAME
  name: IMAGE
  required: true
  value: quay.io/cloudservices/ros-ocp-backend
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Kruize database name
  name: KRUIZE_DB_NAME
  required: true
- description: Kruize image name
  name: KRUIZE_IMAGE
  required: true
  value: quay.io/cloudservices/autotune
- description: Kruize image tag
  name: KRUIZE_IMAGE_TAG
  required: true
- description: Kruize server host
  name: KRUIZE_HOST
  required: true
  value: "ros-ocp-backend-kruize"
- description: Kruize server port
  name: KRUIZE_PORT
  required: true
  value: "10000"
- description: Initial kruize cpu request.
  displayName: KRUIZE CPU Request
  name: KRUIZE_CPU_REQUEST
  required: true
  value: 500m
- description: Initial amount of memory kruize container will request.
  displayName: KRUIZE Memory Request
  name: KRUIZE_MEMORY_REQUEST
  required: true
  value: 1Gi
- description: Maximum amount of memory kruize container can use.
  displayName: KRUIZE Memory Limit
  name: KRUIZE_MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Maximum amount of CPU kruize container can use.
  displayName: KRUIZE CPU Limit
  name: KRUIZE_CPU_LIMIT
  required: true
  value: '1'
- description: Initial cpu request.
  displayName: CPU Request
  name: CPU_REQUEST
  required: true
  value: 500m
- description: Initial amount of memory the container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST
  required: true
  value: 1Gi
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT
  required: true
  value: 1Gi
- description: Maximum amount of CPU the build container can use.
  displayName: CPU Limit
  name: CPU_LIMIT
  required: true
  value: '1'
- description: Is clowder enabled
  name: CLOWDER_ENABLED
  value: "True"
- name: SSL_CERT_DIR
  value: '/etc/ssl/certs:/etc/pki/tls/certs:/system/etc/security/cacerts:/cdapp/certs'
- description: Replica count for api pod
  name: API_REPLICA_COUNT
  value: "1"
- description: Replica count for recommender pod
  name: RECOMMENDER_REPLICA_COUNT
  value: "1"
- description: Time to wait before hitting listRecommendation API
  name: KRUIZE_WAIT_TIME
  value: "120"
- description: Replica count for kruize pod
  name: KRUIZE_REPLICA_COUNT
  value: "1"
