---
apiVersion: v1
kind: Template
metadata:
  name: ros-ocp-backend
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: ros-ocp-backend
  spec:
    envName: ${ENV_NAME}
    dependencies:
    - ingress
    - sources-api
    deployments:
    - name: processor
      replicas: ${{PROCESSOR_REPLICA_COUNT}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start processor"]
        resources:
          requests:
            cpu: ${CPU_REQUEST_ROSOCP}
            memory: ${MEMORY_REQUEST_ROSOCP}
          limits:
            cpu: ${CPU_LIMIT_ROSOCP}
            memory: ${MEMORY_LIMIT_ROSOCP}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: KRUIZE_HOST
            value: ${KRUIZE_HOST}
          - name: KRUIZE_PORT
            value: ${KRUIZE_PORT}
          - name: KRUIZE_WAIT_TIME
            value: ${KRUIZE_WAIT_TIME}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
          - name: SERVICE_NAME
            value: "rosocp-processor"
          - name: CW_LOG_STREAM_NAME
            value: "rosocp-backend"
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
    - name: recommendation-poller
      replicas: ${{POLLER_REPLICA_COUNT}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start recommendation-poller"]
        resources:
          requests:
            cpu: ${CPU_REQUEST_ROSOCP}
            memory: ${MEMORY_REQUEST_ROSOCP}
          limits:
            cpu: ${CPU_LIMIT_ROSOCP}
            memory: ${MEMORY_LIMIT_ROSOCP}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: KRUIZE_HOST
            value: ${KRUIZE_HOST}
          - name: KRUIZE_PORT
            value: ${KRUIZE_PORT}
          - name: KRUIZE_WAIT_TIME
            value: ${KRUIZE_WAIT_TIME}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
          - name: SERVICE_NAME
            value: "rosocp-recommendation-poller"
          - name: CW_LOG_STREAM_NAME
            value: "rosocp-backend"
          - name: LOG_LEVEL
            value: ${RECOMMENDATION_POLLER_LOG_LEVEL}
    - name: api
      replicas: ${{API_REPLICA_COUNT}}
      webServices:
        public:
          enabled: true
          apiPath: cost-management
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start api"]
        resources:
          requests:
            cpu: ${CPU_REQUEST_ROSOCP}
            memory: ${MEMORY_REQUEST_ROSOCP}
          limits:
            cpu: ${CPU_LIMIT_ROSOCP}
            memory: ${MEMORY_LIMIT_ROSOCP}
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /status
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 3
        env:
          - name: PATH_PREFIX
            value: /api
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: RBAC_ENABLE
            value: "${RBAC_ENABLE}"
          - name: DB_POOL_SIZE
            value: ${DB_POOL_SIZE}
          - name: DB_MAX_OVERFLOW
            value: ${DB_MAX_OVERFLOW}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
          - name: SERVICE_NAME
            value: "rosocp-api"
          - name: CW_LOG_STREAM_NAME
            value: "rosocp-api"
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
    - name: housekeeper
      replicas: ${{HOUSEKEEPER_REPLICA_COUNT}}
      podSpec:
        image: ${IMAGE}:${IMAGE_TAG}
        command: ["sh"]
        args: ["-c", "./rosocp db migrate up && ./rosocp start housekeeper --sources"]
        resources:
          requests:
            cpu: ${CPU_REQUEST_ROSOCP}
            memory: ${MEMORY_REQUEST_ROSOCP}
          limits:
            cpu: ${CPU_LIMIT_ROSOCP}
            memory: ${MEMORY_LIMIT_ROSOCP}
        env:
          - name: CLOWDER_ENABLED
            value: ${CLOWDER_ENABLED}
          - name: SSL_CERT_DIR
            value: ${SSL_CERT_DIR}
          - name: SERVICE_NAME
            value: "rosocp-housekeeper-sources"
          - name: CW_LOG_STREAM_NAME
            value: "rosocp-housekeeper"
          - name: LOG_LEVEL
            value: ${LOG_LEVEL}
          - name: KRUIZE_HOST
            value: ${KRUIZE_HOST}
          - name: KRUIZE_PORT
            value: ${KRUIZE_PORT}

    jobs:
      - name: delete-rosocp-partitions
        schedule: ${PARTITION_DELETE_INTERVAL}
        podSpec:
          name: rosocpcronjob
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          restartPolicy: OnFailure
          command: ["sh"]
          args: ["-c", "./rosocp db migrate up && ./rosocp start housekeeper --partitions"]
          env:
            - name: CLOWDER_ENABLED
              value: ${CLOWDER_ENABLED}
            - name: SSL_CERT_DIR
              value: ${SSL_CERT_DIR}
            - name: SERVICE_NAME
              value: "rosocp-housekeeper-partition"
            - name: CW_LOG_STREAM_NAME
              value: "rosocp-housekeeper"
            - name: LOG_LEVEL
              value: ${LOG_LEVEL}

    database:
      name: rosocp
      version: 13
    kafkaTopics:
      - topicName: hccm.ros.events
        partitions: 1
      - topicName: rosocp.kruize.recommendations
        partitions: 1
      - topicName: platform.sources.event-stream
        partitions: 1
    testing:
      iqePlugin: ros-ocp

parameters:
- description : ClowdEnvironment name
  name: ENV_NAME
  required: true
- description: Replica count for processor pod
  name: PROCESSOR_REPLICA_COUNT
  value: "1"
- description: Replica count for recommendation-poller pod
  name: POLLER_REPLICA_COUNT
  value: "1"
- description: Image NAME
  name: IMAGE
  required: true
  value: quay.io/redhat-services-prod/insights-management-tenant/insights-ocp-resource-optimization/ros-ocp-backend
- description: Image tag
  name: IMAGE_TAG
  required: true
- description: Kruize server host
  name: KRUIZE_HOST
  required: true
  value: "kruize-recommendations"
- description: Kruize server port
  name: KRUIZE_PORT
  required: true
  value: "10000"
- description: Initial cpu request.
  displayName: CPU Request
  name: CPU_REQUEST_ROSOCP
  required: true
  value: 500m
- description: Initial amount of memory the container will request.
  displayName: Memory Request
  name: MEMORY_REQUEST_ROSOCP
  required: true
  value: 1Gi
- description: Maximum amount of memory the container can use.
  displayName: Memory Limit
  name: MEMORY_LIMIT_ROSOCP
  required: true
  value: 1Gi
- description: Maximum amount of CPU the build container can use.
  displayName: CPU Limit
  name: CPU_LIMIT_ROSOCP
  required: true
  value: '1'
- description: Is clowder enabled
  name: CLOWDER_ENABLED
  value: "True"
- name: SSL_CERT_DIR
  value: '/etc/ssl/certs:/etc/pki/tls/certs:/system/etc/security/cacerts:/cdapp/certs'
- description: Replica count for api pod
  name: API_REPLICA_COUNT
  value: "1"
- description: Replica count for recommender pod
  name: RECOMMENDER_REPLICA_COUNT
  value: "1"
- description: Replica count for recommender pod
  name: HOUSEKEEPER_REPLICA_COUNT
  value: "1"
- description: Time to wait before hitting listRecommendation API
  name: KRUIZE_WAIT_TIME
  value: "120"
- description: Enable the RBAC
  name: RBAC_ENABLE
  value: "true"
- name: LOG_LEVEL
  value: 'INFO'
- name: RECOMMENDATION_POLLER_LOG_LEVEL
  value: 'INFO'
- name: PARTITION_DELETE_INTERVAL
  value: "0 0 */15 * *" # Runs at 12:00 AM, every 15 days.
