-- Replace variation columns: drop legacy raw columns (and any prior *_pct columns from partial deploys), then add percent-of-request columns with explicit *_pct names.
ALTER TABLE namespace_recommendation_sets
    DROP COLUMN IF EXISTS cpu_variation_short_cost,
    DROP COLUMN IF EXISTS cpu_variation_short_performance,
    DROP COLUMN IF EXISTS cpu_variation_medium_cost,
    DROP COLUMN IF EXISTS cpu_variation_medium_performance,
    DROP COLUMN IF EXISTS cpu_variation_long_cost,
    DROP COLUMN IF EXISTS cpu_variation_long_performance,
    DROP COLUMN IF EXISTS memory_variation_short_cost,
    DROP COLUMN IF EXISTS memory_variation_short_performance,
    DROP COLUMN IF EXISTS memory_variation_medium_cost,
    DROP COLUMN IF EXISTS memory_variation_medium_performance,
    DROP COLUMN IF EXISTS memory_variation_long_cost,
    DROP COLUMN IF EXISTS memory_variation_long_performance,
    DROP COLUMN IF EXISTS cpu_variation_short_cost_pct,
    DROP COLUMN IF EXISTS cpu_variation_short_performance_pct,
    DROP COLUMN IF EXISTS cpu_variation_medium_cost_pct,
    DROP COLUMN IF EXISTS cpu_variation_medium_performance_pct,
    DROP COLUMN IF EXISTS cpu_variation_long_cost_pct,
    DROP COLUMN IF EXISTS cpu_variation_long_performance_pct,
    DROP COLUMN IF EXISTS memory_variation_short_cost_pct,
    DROP COLUMN IF EXISTS memory_variation_short_performance_pct,
    DROP COLUMN IF EXISTS memory_variation_medium_cost_pct,
    DROP COLUMN IF EXISTS memory_variation_medium_performance_pct,
    DROP COLUMN IF EXISTS memory_variation_long_cost_pct,
    DROP COLUMN IF EXISTS memory_variation_long_performance_pct;

ALTER TABLE namespace_recommendation_sets
    ADD COLUMN cpu_variation_short_cost_pct FLOAT,
    ADD COLUMN cpu_variation_short_performance_pct FLOAT,
    ADD COLUMN cpu_variation_medium_cost_pct FLOAT,
    ADD COLUMN cpu_variation_medium_performance_pct FLOAT,
    ADD COLUMN cpu_variation_long_cost_pct FLOAT,
    ADD COLUMN cpu_variation_long_performance_pct FLOAT,
    ADD COLUMN memory_variation_short_cost_pct FLOAT,
    ADD COLUMN memory_variation_short_performance_pct FLOAT,
    ADD COLUMN memory_variation_medium_cost_pct FLOAT,
    ADD COLUMN memory_variation_medium_performance_pct FLOAT,
    ADD COLUMN memory_variation_long_cost_pct FLOAT,
    ADD COLUMN memory_variation_long_performance_pct FLOAT;
